<?php

namespace App\Filament\Resources\LessonResource\Pages;

use App\Filament\Resources\LessonResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Filament\Tables;

class ListLessons extends ListRecords
{
    protected static string $resource = LessonResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    protected function configureDeleteAction(Tables\Actions\DeleteAction $action): void
    {
        $action->before(function () use ($action){
            Helpers::subtractDeletedLessonDurationFromCourseDuration($action->getRecord());
        });
        parent::configureDeleteAction($action); // TODO: Change the autogenerated stub
    }

    protected function configureDeleteBulkAction(Tables\Actions\DeleteBulkAction $action): void
    {
        $action->before(function () use ($action){
            foreach ($action->getRecords() as $record){
                Helpers::subtractDeletedLessonDurationFromCourseDuration($record);
            }
        });
        parent::configureDeleteBulkAction($action); // TODO: Change the autogenerated stub
    }
}
