<?php

namespace App\Filament\Resources\LessonResource\Pages;

use App\Filament\Resources\LessonResource;
use Filament\Actions;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\ViewRecord;

class ViewLesson extends ViewRecord
{
    protected static string $resource = LessonResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\EditAction::make(),
            Actions\DeleteAction::make()
        ];
    }

    protected function configureDeleteAction(DeleteAction $action): void
    {
        $action->before(function () use ($action){
            Helpers::subtractDeletedLessonDurationFromCourseDuration($action->getRecord());
        });
        parent::configureDeleteAction($action); // TODO: Change the autogenerated stub
    }
}
